# Discord info
token: "Place token here"
owner-id: "place your discord id here"
# GitHub Info
username: "Put github username here"
personal-access-token: "put your personal access token here"
# Server Info
port: "put port here"
secrets:
  - "replace me with something secure"
  - "feel free to add more secrets here"
  - "these are basically tokens, or passwords"
# Database Info
db_host: "put database host here"
db_port: 0000
db_username: "put database username here"
db_password: "put database password here"
db_encryption: truefalse
